# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-05 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='category',
            new_name='user',
        ),
    ]
